---
exclude_paths:
  - 'wp-content/themes/<theme-name>/acf-json/**'
  - 'wp-content/themes/<theme-name>/frontend/node_modules/**'
  - 'wp-content/themes/<theme-name>/frontend/dist/**'
  - 'wp-content/themes/<theme-name>/frontend/static/**'
  - 'wp-content/themes/<theme-name>/frontend/.cache/**'
  - '**/vendor/**'
  - '**/benchmarks/**/*'
  - '*.yml'
  - '*.md'
  - '*.sassrc'
  - '*.json'
  - '*.sh'
  - '*.gitignore'
  - '*.json'
  - '*.lock'
  - '*.txt'
  - '*.xml'
  - '*.css'
  - '*.editorconfig'